/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_schwiebert_abl4j_random_NativeRandom */

#ifndef _Included_org_schwiebert_abl4j_random_NativeRandom
#define _Included_org_schwiebert_abl4j_random_NativeRandom
#ifdef __cplusplus
extern "C" {
#endif
#undef org_schwiebert_abl4j_random_NativeRandom_serialVersionUID
#define org_schwiebert_abl4j_random_NativeRandom_serialVersionUID 3905348978240129619LL
#undef org_schwiebert_abl4j_random_NativeRandom_multiplier
#define org_schwiebert_abl4j_random_NativeRandom_multiplier 25214903917LL
#undef org_schwiebert_abl4j_random_NativeRandom_addend
#define org_schwiebert_abl4j_random_NativeRandom_addend 11LL
#undef org_schwiebert_abl4j_random_NativeRandom_mask
#define org_schwiebert_abl4j_random_NativeRandom_mask 281474976710655LL
#undef org_schwiebert_abl4j_random_NativeRandom_serialVersionUID
#define org_schwiebert_abl4j_random_NativeRandom_serialVersionUID 1LL
/*
 * Class:     org_schwiebert_abl4j_random_NativeRandom
 * Method:    next
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_schwiebert_abl4j_random_NativeRandom_next
  (JNIEnv *, jobject);

/*
 * Class:     org_schwiebert_abl4j_random_NativeRandom
 * Method:    setSeed
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_schwiebert_abl4j_random_NativeRandom_setSeed
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
